### ISSUE TITLE
loss of wifi

### ISSUE THREAD

**Issue by davlaw** [LoopOnCode/AirSense#12]
I have a bridge between the air-sense and my main wifi.  Bridge crashed during the night and loss of wifi to devices connected to it.   Bridge service restored all devices reconnected except the airsense.  

Does it have any time out that could be employed to work with is besides power cycling the airsense device?  Or maybe this would be more of an esphome issue?

**Comment by LoopOnTech** [comment]
Hi,

The fallback AP will initiate after 1 minute of not being able to connect to your network.
Hope that helps.

Thank you
