### ISSUE TITLE
Esphome  2024.3.0

### ISSUE THREAD

**Issue by davlaw** [LoopOnCode/AirSense#13]
Guess we got too big for esphome 2024.3.0

Error: The program size (1889392 bytes) is greater than maximum allowed (1835008 bytes)
*** [checkprogsize] Explicit exit, status 1
RAM:   [==        ]  18.7% (used 61284 bytes from 327680 bytes)
Flash: [==========]  103.0% (used 1889392 bytes from 1835008 bytes)
========================= [FAILED] Took 20.05 seconds =========================

**Comment by davlaw** [comment]
gonna guess this might be a bosch problem or something close. They did appear to update this library last month.

After cleaning build files I get this 


Library Manager: Installing git+https://github.com/boschsensortec/Bosch-BSEC2-Library.git#v1.4.2200
INFO Installing git+https://github.com/boschsensortec/Bosch-BSEC2-Library.git#v1.4.2200
git version 2.39.2
Cloning into '/data/cache/platformio/cache/tmp/pkg-installing-89tszc6c'...
Note: switching to 'aeb4e4931fccdd8524c0b40d14aa2c5eec599ff6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Library Manager: BSEC2 Software Library@1.4.2200+sha.aeb4e49 has been installed!

**Comment by LoopOnTech** [comment]
Hi, thank you for raising this issue.
Unfortunately I am not abe to replicate this. AirSenses are currently running on ESPHome version 2024.6.6. Please try to update again or recompile locally.

Thank you
