### ISSUE TITLE
FWIW wifi disconnects and Wifi Auth Expired

### ISSUE THREAD

**Issue by davlaw** [LoopOnCode/AirSense#20]
Kinda been working thru WiFi disconnects , WiFi Auth Expired issues.

I read a post https://community.home-assistant.io/t/esphome-wifi-auth-expired/443790/1

Several things to try but what worked for me was 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 8.5

Bingo, stays connected , no drops.

Hope I'm not jinking it!!   Currently working with esphome 2024.8.0, but it started with 2024.7.x, not sure which

**Comment by LoopOnTech** [comment]
Hi @davlaw ,

Can I ask, how often was the device disconnecting? And how far away from your network AP was the device?

Thank you

**Comment by davlaw** [comment]
Ended up adding the following, output_power

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 10.0
