### ISSUE TITLE
Pleas add a donation or paypal address!

### ISSUE THREAD

**Issue by guelz** [LoopOnCode/AirSense#6]
Borrowing all of your code made my C3-BME680-LD210-VeluxWindow_thingy finally work! So far only one, second one refuses to. But I'll get there..
Thank you!

**Comment by LoopOnTech** [comment]
Hi! Glad it worked for you! Hope the second one is working too now.

Happy to accept a [coffee donation](https://paypal.me/LoopOnTech) :) 

Thanks!
